version: '2'

services:

  consul:
    build: ./consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
      - 8600:8600

  app:
    build: ./app
    ports:
      - 8080:8080
      - 8000:8000
    links:
      - consul:consul
    depends_on:
      - "consul"
